### PR TITLE
Revert "add expect_macro"

### PR DESCRIPTION
**Pull request by vitiral**
This reverts commit bc293ec80536888080c596d14d54da99abc0557c.

Okay, let's see if we can do this right this time... 😄

### CODE REVIEW

**Review by killercup — APPROVED** [review]
👍 <https://github.com/rust-crates/ergo_std/pull/3#issuecomment-364171128>

**Comment by vitiral** [comment]
Okay so NOW I specify:

bors r= @killercup

**Comment by vitiral** [comment]
did I do it right this time? 😆

**Comment by killercup** [comment]
Yes! :tada:

(I could've also written `bors r+` myself but only people you specified in your bors config are allowed to do that)

**Comment by vitiral** [comment]
you _should_ be able to approve things. I set bors to allow anyone from the repo editors group (and nobody is specified in the bors config)

**Pull request merged**
